# Generated by Django 2.1.3 on 2018-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='中国大陆手机号', max_length=11, null=True, unique=True, verbose_name='电话'),
        ),
    ]
