# Generated by Django 2.1.3 on 2018-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181116_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=30, null=True, unique=True, verbose_name='姓名'),
        ),
    ]
