# Generated by Django 2.1.3 on 2018-11-21 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resources', '0002_auto_20181119_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_name', models.ForeignKey(on_delete=True, related_name='StudentsParents_parent', to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(on_delete=True, related_name='StudentsParents_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.ForeignKey(on_delete=True, related_name='StudentsTeachers_student', to=settings.AUTH_USER_MODEL)),
                ('teacher_name', models.ForeignKey(on_delete=True, related_name='StudentsTeachers_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
