# Generated by Django 2.1.3 on 2018-11-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_studentsparents_studentsteachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersgroups',
            old_name='username',
            new_name='name',
        ),
    ]
