# Generated by Django 2.1.3 on 2018-11-21 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0006_auto_20181121_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroups',
            name='group',
            field=models.ForeignKey(on_delete=False, to='Resources.Groups'),
        ),
        migrations.AlterField(
            model_name='usersgroups',
            name='name',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
