# Generated by Django 2.1.3 on 2018-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0008_auto_20181121_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsLives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_name', models.ForeignKey(on_delete=True, to='Resources.Lives')),
                ('student_name', models.ForeignKey(on_delete=True, to='Resources.Students')),
            ],
        ),
    ]
