# Generated by Django 2.1.3 on 2018-11-22 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0009_lives_studentslives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentslives',
            name='student_name',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
