# Generated by Django 2.1.3 on 2018-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0013_image_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_test',
            name='file',
            field=models.ImageField(upload_to='static_dist/images'),
        ),
    ]
