# Generated by Django 2.1.3 on 2018-11-25 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resources', '0014_auto_20181125_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersVipCustoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VipCustoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='image_test',
        ),
        migrations.AddField(
            model_name='usersvipcustoms',
            name='vipcourses',
            field=models.ForeignKey(on_delete=True, to='Resources.VipCustoms'),
        ),
    ]
