# Generated by Django 2.1.3 on 2018-11-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0015_auto_20181125_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersvipcustoms',
            old_name='vipcourses',
            new_name='vipcustom',
        ),
    ]
