# Generated by Django 2.1.3 on 2018-11-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0016_auto_20181126_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipCustomsCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=True, to='Resources.Courses')),
                ('vipcustom', models.ForeignKey(on_delete=True, to='Resources.VipCustoms')),
            ],
        ),
    ]
